# Development configuration for LG-SOTF

# Database configuration
database:
  host: localhost
  port: 5432
  database: lg_sotf_dev
  username: lg_sotf
  password: lg_sotf_dev_password
  pool_size: 5
  max_overflow: 10

# Redis configuration
redis:
  host: localhost
  port: 6379
  password: null
  db: 0
  max_connections: 5

# Agent configuration
agents:
  ingestion:
    batch_size: 10
    polling_interval: 30
    max_concurrent_alerts: 5
  
  triage:
    confidence_threshold: 70
    enable_ml_scoring: true
    ml_model_path: "models/triage_model.pkl"
  
  analysis:
    max_iterations: 3
    timeout_seconds: 30
    enable_tool_caching: true
  
  human_loop:
    escalation_threshold: 40
    max_escalation_level: 3
    response_timeout_hours: 24

# Tool configuration
tools:
  siem:
    splunk:
      base_url: "https://splunk-dev.example.com:8089"
      token: "dev_token"
      index: "security"
      search_timeout: 30
    
    qradar:
      base_url: "https://qradar-dev.example.com"
      token: "dev_token"
      timeout: 30
  
  intel:
    virustotal:
      api_key: "dev_virustotal_key"
      timeout: 10
      rate_limit: 4  # requests per minute
    
    recorded_future:
      api_key: "dev_recorded_future_key"
      timeout: 15
  
  sandbox:
    joe_sandbox:
      base_url: "https://joesandbox-dev.example.com"
      api_key: "dev_joe_sandbox_key"
      timeout: 300  # 5 minutes
  
  edr:
    crowdstrike:
      base_url: "https://api.crowdstrike.com"
      client_id: "dev_client_id"
      client_secret: "dev_client_secret"
      timeout: 30

# Storage configuration
storage:
  backend: "postgresql"
  connection_string: "postgresql://lg_sotf:lg_sotf_dev_password@localhost:5432/lg_sotf_dev"
  
  redis:
    connection_string: "redis://localhost:6379/0"
    default_ttl: 3600  # 1 hour

# Logging configuration
logging:
  level: "DEBUG"
  format: "json"
  file_path: "logs/lg_sotf_dev.log"
  max_file_size: "10MB"
  backup_count: 5

# Security configuration
security:
  encryption_key: "dev_encryption_key_32_bytes_long___"
  jwt_secret: "dev_jwt_secret_32_bytes_long______"
  session_timeout: 3600
  max_login_attempts: 5

# Monitoring configuration
monitoring:
  metrics_enabled: true
  metrics_port: 8090
  tracing_enabled: true
  tracing_sampling_rate: 0.1

# Development settings
development:
  debug_mode: true
  auto_reload: true
  mock_external_services: true
  test_data_path: "tests/fixtures"